
[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 12.0

[font.bold]
family = "Pragmata Pro"
style = "Regular" 
#style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Pragmata Pro"
style = "Italic"

[font.normal]
family = "Pragmata Pro"
style = "Mono"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Alt"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
#decorations = "buttonless"
#dynamic_padding = false
opacity = 1.0

[general]
live_config_reload = true

# Default colors
[colors.primary]
background = '#2c2c2c'
foreground = '#d6d6d6'

dim_foreground    = '#dbdbdb'
bright_foreground = '#d9d9d9'

# Cursor colors
[colors.cursor]
text   = '#2c2c2c'
cursor = '#d9d9d9'

# Normal colors
[colors.normal]
black   = '#1c1c1c'
red     = '#bc5653'
green   = '#909d63'
yellow  = '#ebc17a'
blue    = '#7eaac7'
magenta = '#aa6292'
cyan    = '#86d3ce'
white   = '#cacaca'

# Bright colors
[colors.bright]
black   = '#636363'
red     = '#bc5653'
green   = '#909d63'
yellow  = '#ebc17a'
blue    = '#7eaac7'
magenta = '#aa6292'
cyan    = '#86d3ce'
white   = '#f7f7f7'

# Dim colors
[colors.dim]
black   = '#232323'
red     = '#74423f'
green   = '#5e6547'
yellow  = '#8b7653'
blue    = '#556b79'
magenta = '#6e4962'
cyan    = '#5c8482'
white   = '#828282'


